import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import avatar from "../public/avatar.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>DK Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script>document.documentElement.classList.add('js')</script>
        
      </Head>
      <main className=" bg-gray-300 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="mb-">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl">Next.Js & Tailwind</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/1xJ0grPAab9ClEHyEMQjZqFqRiUKUnuYV/edit?usp=sharing&ouid=105584303304321756439&rtpof=true&sd=true"
                  target="_blank">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-10">
            <h2 className="text-5xl py-2 text-teal-500 font-medium dark:text-teal-400 md:text-6xl">
              David Kim
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Minimalist
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I'm a junior full stack developer with a passion for creating
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/djk88" target="_blank"><AiFillGithub /></a>
              <a href="https://www.linkedin.com/in/david-kim-0054b46b/" target="_blank"><AiFillLinkedin /></a>
              <a href="mailto:davekim88@gmail.com"><AiFillMail /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={avatar} layout="fill" objectFit="cover" alt=""/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Hello! My name is David Kim, and I'm a junior web developer currently enrolled in the Software Systems Development course at <span className="text-teal-500">BCIT</span>. This portfolio documents my journey through the program, showcasing my skills and projects as I progress towards graduation in May 2023.
            </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Prior to my foray into web development, I spent over a decade working in the automotive industry, with experience ranging from lube technician to parts manager for brands like <span className="text-teal-500">Porsche, BMW, Hyundai, and Honda</span>. Through this work, I honed my problem-solving skills, attention to detail, and ability to work in fast-paced environments.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My transition to web development was inspired by a <span className="text-teal-500">desire</span> to expand my skill set and <span className="text-teal-500">challenge</span> myself in a new field. Throughout my time in the Software Systems Development course, I've learned new programming languages and frameworks, built a variety of web applications, and collaborated with other student developers to create effective solutions.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a web developer, my <span className="text-teal-500">goal</span> is to create engaging, user-friendly applications that help solve real-world problems. I'm particularly interested in the intersection of <span className="text-teal-500">technology</span> and <span className="text-teal-500">design</span>, and how the two can work together to create intuitive and effective experiences for users.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Thank you for taking the time to explore my portfolio. If you're interested in working together or have any questions, please don't hesitate to reach out!
              </p>      
          </div>
          <div className="lg:flex gap-10">
            <div className="bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front End Development
              </h3>
              <h4 className="py-4 text-teal-600">Technologies</h4>
              <p className="text-gray-800 py-1">HTML5</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">Javascript</p>
            </div>
            <div className="bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Back End Development
              </h3>
              <h4 className="py-4 text-teal-600">Technologies</h4>
              <p className="text-gray-800 py-1">ASP.Net</p>
              <p className="text-gray-800 py-1">C-Sharp</p>
              <p className="text-gray-800 py-1">Node.js</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">SQL</p>
            </div>
            <div className=" bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">Amazon Web Services</h3>
              <h4 className="py-4 text-teal-600">Technologies</h4>
              <p className="text-gray-800 py-1">S3 Bucket</p>
              <p className="text-gray-800 py-1">API Gateway</p>
              <p className="text-gray-800 py-1">Lambda Functions</p>
              <p className="text-gray-800 py-1">Cognito</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            This section showcases the projects I've worked on throughout my web development journey, including both individual and collaborative projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Each thumbnail below links to the corresponding GitHub repository, where you can view the code and learn more about the project. I've included a brief description of each project below to give you an idea of what it's all about.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I'm constantly learning and growing as a web developer, and am always excited to take on new projects and challenges. If you have any questions or are interested in collaborating on a project, please don't hesitate to reach out. Thanks for checking out my portfolio!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            <a href="https://github.com/djk88/reactavision">
              <Image
                className="rounded-lg object-cover shadow-lg"
                width={"100%"}
                height={"100%"}
                src={web1}
                alt="movie website built with React and CSS"
              />
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Reactavision</span>: This project was completed as part of the React course and focuses on working with the TMDB API. I worked on this project with another team member and used React and CSS.
              </p>
              </a>
              <a href="https://reactavision.vercel.app/" target="_blank"><span className="text-teal-500">Click here for a demo!</span></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="#">
              <Image
                className="rounded-lg object-cover shadow-lg"
                width={"100%"}
                height={"100%"}
                src={web2}
                alt="fake tourism website built with html5, css, and javascript"
              />
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Bali Tourism website</span>: This project was completed as part of the front-end web course and involved building a fake tourism website to a country of our choosing. I worked on this project individually and used HTML5, CSS and Javascript.
              </p>
              
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="#">
              <Image
                className="rounded-lg object-cover shadow-lg"
                width={"100%"}
                height={"100%"}
                src={web3}
                alt="fake bank website build with ASP.Net and C-Sharp"
              />
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Bank Website</span>: This project was completed as part of the ASP.Net course and involved building a fake bank site. This website allows users to register/login to see their own accounts. I worked on this project individually and used ASP.Net.
              </p>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="#">
              <Image
                className="rounded-lg object-cover shadow-lg"
                width={"100%"}
                height={"100%"}
                src={web4}
                alt="fake bank website build with ASP.Net and C-Sharp"
              />
             <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Portfolio</span>: This project was completed as part of the Angular course and involved building a portfolio. This website allows users to filter by category or tag. I worked on this project individually and used Angular and CSS.
              </p>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/ceilidh-ashcroft-bcit/CakeFactory">
              <Image
                className="rounded-lg object-cover shadow-lg"
                width={"100%"}
                height={"100%"}
                src={web5}
                alt="fake bank website build with ASP.Net and C-Sharp"
              />
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Cake Factory</span>: This project was completed as part of the ASP.NET internal project and involved building a business website that sells cakes. This website allows users to register/login and purchase a pre made cake or create a custom cake. Users are also able to see their purchase history once logged in as well. I worked on this project with 4 other team members.
              </p>
              </a>
            </div>
          </div>
        </section>
      </main>
      <script src="https://unpkg.com/taos@1.0.2/dist/taos.js"></script>
    </div>
  );
}
